name: Deploy to Azure Function App (Dev Slot)

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Login to Azure using Publish Profile
      - name: Login to Azure
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_DEV }}

      # Step 5: Deploy to Azure Function App (Dev Slot)
      - name: Deploy to Azure Function App (Dev Slot)
        uses: Azure/functions-action@v1
        with:
          app-name: 'devdocgenv2'  
          slot-name: 'devdocgenv2-dev'  
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_DEV }}
